name: Deploy Mosaic to GitHub Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Allows manual triggering of the workflow
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Stencil project
        run: npm run build

      - name: Upload Stencil build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./www  # Replace with your Stencil build output directory if different

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
